### ISSUE TITLE
Add a search option to the Picker

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/MediaPicker-iOS#257] opened 2017-10-31 14:33 UTC
It would be nice to allow users search for the media, something like this:

<img width="545" alt="screen shot 2017-10-31 at 14 29 50" src="https://user-images.githubusercontent.com/651601/32229338-79093eb8-be48-11e7-804d-aec880565020.png">

Related to this request on the media app: https://github.com/wordpress-mobile/WordPress-iOS/issues/7680

This is basically to allows us to have Search possibilities anywhere we use the picker.

**Comment by etoledom** [comment] 2017-11-04 04:21
Hi everyone! :]

I'm on a trail period right now and I was assigned this ticket.
I have two possible implementations in mind to add this functionality, both of which would modify the `WPMediaPicker` component.

**1- Add a `UISearchController` to `WPMediaPickerViewController.navigationItem.searchController`**

![search_1](https://user-images.githubusercontent.com/9772967/32402178-10f61f0a-c0fd-11e7-9d72-08b6df897039.png)

pros:
- Elegant and modern UI
- Auto show / hide on scroll
- Simple to implement
- Could be always available and hidden by default

cons:
- iOS 11+
- Needs the  `WPMediaPickerViewController` to be embedded in a `UINavigationController`
- Won't work in the `MediaLibraryViewController`
- UI inconsistent with the rest of the WP app (different from all the other search bars)

---

**2- Add the `UISearchBar` as a `SupplementaryView` header of the picker collectionsView**

![search_2](https://user-images.githubusercontent.com/9772967/32402181-19e3bc80-c0fd-11e7-98f8-9d756dbf1ba4.png)


pros:
- Support iOS 9+
- Doesn't need an external `UINavigationController`
- Can be used in the `MediaLibraryViewController`, replacing the current searchBar
- Consistent search UI within the WP app

cons:
- It conflicts with `WPMediaCapturePreviewCollectionView` (since it also uses supplementary views)
- Additional options to show or not show the search bar
- 'Older' look
- it allows a searchBar in `WPInputMediaPickerViewController` (which is problematic without a keyboard)

---
There's another option that is adding a searchBar in the `WPMediaPickerViewController.navigationItem.titleView`, but I'm not considering it since it hides the `navigationItem.rightBarButtonItems`, which are used for several actions related to media pickers.

I'm personally leaning towards option 2, mostly because of its visual consistency with the rest of the WP app and because of its compatibility with iOS 10. But in case you are planing to convert all the search bars to the iOS 11 style, and if the compatibility with iOS 10 is not crucial, the first option would be preferable.

To resolve the conflict of the search bar with the `capturePreviewCell` I'm planning to put together a mix of option settings, precedence, and toggling to also support both possibilities in the same picker (like in the `GravatarPickerViewController`).

Please let me know which option strikes you as more appropriate. Also any other suggestions or ideas are always welcome 😁.

Thank you!

**Comment by SergioEstevao** [comment] 2017-11-04 10:31
I agree with you @etoledom that option 2 looks the more adequate while we need to keep compatibility with iOS10. 
As you say above I think the option of showing a search bar should be configurable using options, and I think you can present the search and the capture at the same time on the header cells if both are enabled.

@frosty do you want to give some input here too? You are the master of search bars :) .

**Comment by frosty** [comment] 2017-11-06 10:59
Hey @etoledom! Great summary of the available options! So I agree that option 2 is probably the better of the two options right now. However, I would like us to eventually transition the main app to use the new navigationItem-owned search controllers. 

One of the main issues there is fixing the style of the search field. There's no easy way to customise it that I could find, short of setting it to an image with rounded corners we'd need to add ourselves, or to go through the subviews of the search bar and set the background colour of the appropriate view. We're also still supporting iOS 10 so that would add some extra complexity to the code.

A third option would be to simply add it as as subview of `WPNavigationMediaPickerController` (embed the collection view and search bar in a stack view) – this is what we currently do in the Media Library section of WPiOS right now, and it would allow us to keep the current supplementary view for the capture cell. What do you think?

**Comment by etoledom** [comment] 2017-11-07 17:24
Hey @frosty! Nice to meet you!
I see what you mean. After @SergioEstevao's feedback, I made some changes to the second option and basically ended up doing something very similar to what you proposed.

To avoid conflicts with the capture cell I:
- Added the search bar as a subView.
- Added the collection view as a subView behind the search bar.
- Managed the top inset to avoid the content appearing behind the search bar.
- For all that to be possible I transformed the `WPMediaPickerViewController` from a UICollectionView subclass to a `UIViewController` subclass.
This last change was something I initially tried to avoid, but instead of fighting with UIKit I decided to embrace it and implemented the search bar in a way that UIKit finds more comfortable. 😆

Why not stack views?
I agree that using stack views is a very good option. It makes the management of the layout simpler, but there’s a UI detail that I always appreciate, which is the scroll content visible behind translucent bars. I believe it is a nice touch worth fighting for :]. What do you think?

I’m planning a PR later today so you can take a closer look at what I´ve done so far! From what I see, everything works pretty well in both iOS 10 and 11, including iPhone X (sim).

**Comment by SergioEstevao** [comment] 2017-11-07 21:36
@etoledom couldn't the searchbar be part of the header view of the collectionView? a StackView inside the header?

**Comment by etoledom** [comment] 2017-11-08 03:34
@SergioEstevao The problem I had with the searchBar as a supplementaryView was that the Search Controller was moving the searchBar around when activating / deactivating search. It was difficult to troubleshoot this kind of unexpected behaviour.

Another problem was that the searchBar was losing its firstResponder whenever collectionView reloaded. That’s why I started looking for other possibilities. 

This other implementation is actually quite simple and problem-free (so far 😅). I´m preparing a PR right now.

**Closed** 2017-11-10 12:12 UTC
Labels: enhancement
